title: "Digital Skills for Modern Professionals"
description: "A comprehensive course covering digital marketing, remote work, collaboration, digital security, and social media for career transition"
author: "Gabriel Aloho"
baseurl: "/digital-skills-for-marketing"  # Keep URL same to avoid breaking links
url: "https://gabaloho.github.io"

# Theme
remote_theme: pages-themes/hacker@v0.2.0

# Markdown processor
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-remote-theme 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - README.md

# Exclude files from processing
exclude:
  - .gitignore
  - LICENSE
  - vendor/
  - Gemfile*

# Show downloads (optional for Hacker theme)
show_downloads: false

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X